# Generated by Django 4.2.29 on 2026-03-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-match_score', '-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='company_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Optional cover letter'),
        ),
        migrations.AddField(
            model_name='application',
            name='score_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_note',
            field=models.TextField(blank=True, help_text='Internal note visible to company only'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='label',
            field=models.CharField(blank=True, help_text="Optional label, e.g. 'Software Engineer Resume v2'", max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.resume'),
        ),
    ]
