# Generated by Django 4.2.29 on 2026-03-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_deadline_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification_required',
            field=models.CharField(blank=True, choices=[('', 'Any / Not specified'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD / Doctorate')], default='', help_text='Minimum qualification level required', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(default=0, help_text='Minimum years of experience required'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Detailed role requirements'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, help_text='Key responsibilities'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
