# Generated by Django 4.2.29 on 2026-03-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_alter_resume_options_and_more'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screeningresult',
            options={'ordering': ['-screened_at']},
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error detail if screening failed'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='missing_skills',
            field=models.TextField(blank=True, help_text='Required job skills not found in the resume'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='summary',
            field=models.TextField(blank=True, help_text="AI-generated summary of the candidate's fit"),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='extracted_skills',
            field=models.TextField(blank=True, help_text="Skills extracted from the candidate's resume"),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='matched_skills',
            field=models.TextField(blank=True, help_text='Skills that matched the job requirements'),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='similarity_score',
            field=models.FloatField(default=0, help_text='Cosine similarity score between resume and job description (0–100)'),
        ),
    ]
