# Generated by Django 4.2.29 on 2026-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_screeningresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='cosine_score',
            field=models.FloatField(default=0, help_text='Raw cosine similarity component score (0–100)'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='experience_score',
            field=models.FloatField(default=0, help_text='Experience match component score (0–100)'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='qualification_score',
            field=models.FloatField(default=0, help_text='Qualification match component score (0–100)'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='skill_score',
            field=models.FloatField(default=0, help_text='Skill match component score (0–100)'),
        ),
    ]
