# Generated by Django 4.2.29 on 2026-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_profile_picture_companyprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
